"use client";

import { useState } from "react";
import Link from "next/link";

export default function GeneratePage() {
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [lyrics, setLyrics] = useState("");

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setLoading(true);
    setLyrics("");
    
    try {
      // TODO: Replace with actual API call when backend is ready
      // Simulating API call for now
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      setLyrics(`[Verse 1]
This is a placeholder for generated lyrics
Based on your prompt: "${prompt}"
The actual lyrics will be generated by AI agents
Using LangGraph, RAG, and local LLMs

[Chorus]
Real implementation coming soon
With streaming responses
And beautiful melodies
Generated just for you

[Bridge]
ChromaDB for context
Ollama for the brain
FastAPI for the speed
React for the gain

[Verse 2]
Multi-agent system at work
Planning, generating, refining
Creating lyrics that spark
Your imagination shining
`);
    } catch (error) {
      console.error("Error generating lyrics:", error);
      setLyrics("Error generating lyrics. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Link 
            href="/"
            className="text-blue-600 hover:text-blue-700 mb-4 inline-block"
          >
            ← Back to Home
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            Generate Lyrics
          </h1>
          <p className="text-gray-600">
            Describe the song you want, and AI will create lyrics for you
          </p>
        </div>

        {/* Input Section */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
          <label className="block mb-2 font-semibold text-gray-900">
            Song Description
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="E.g., 'A love song about missing someone, acoustic guitar, melancholic'"
            className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
            rows={4}
          />
          
          <button
            onClick={handleGenerate}
            disabled={loading || !prompt.trim()}
            className="mt-4 px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition"
          >
            {loading ? "Generating..." : "Generate Lyrics"}
          </button>
        </div>

        {/* Output Section */}
        {(lyrics || loading) && (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <h2 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <span>Generated Lyrics</span>
              {loading && (
                <span className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></span>
              )}
            </h2>
            
            {loading ? (
              <div className="space-y-2">
                <div className="h-4 bg-gray-200 rounded animate-pulse w-3/4"></div>
                <div className="h-4 bg-gray-200 rounded animate-pulse w-full"></div>
                <div className="h-4 bg-gray-200 rounded animate-pulse w-5/6"></div>
                <div className="h-4 bg-gray-200 rounded animate-pulse w-2/3"></div>
              </div>
            ) : (
              <pre className="whitespace-pre-wrap font-mono text-sm text-gray-800 bg-gray-50 p-4 rounded-lg">
                {lyrics}
              </pre>
            )}
          </div>
        )}

        {/* Info */}
        <div className="mt-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <p className="text-sm text-yellow-800">
            <strong>Note:</strong> This is a placeholder UI. The actual lyrics generation will be implemented in the backend using LangGraph agents, RAG with ChromaDB, and Ollama LLM.
          </p>
        </div>
      </div>
    </main>
  );
}

