"""add_mixing_feedback_learning_tables

Revision ID: add_mixing_feedback_learning
Revises: 41181f128be7
Create Date: 2025-12-05 17:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_mixing_feedback_learning"
down_revision: Union[str, None] = "41181f128be7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mixing_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=True),
        sa.Column("mixing_config_id", sa.UUID(), nullable=True),
        sa.Column("overall_mixing_rating", sa.Integer(), nullable=True),
        sa.Column("vocals_clarity_rating", sa.Integer(), nullable=True),
        sa.Column("music_balance_rating", sa.Integer(), nullable=True),
        sa.Column("stereo_width_rating", sa.Integer(), nullable=True),
        sa.Column("eq_quality_rating", sa.Integer(), nullable=True),
        sa.Column("reverb_quality_rating", sa.Integer(), nullable=True),
        sa.Column("pesq_score", sa.Float(), nullable=True),
        sa.Column("stoi_score", sa.Float(), nullable=True),
        sa.Column("mos_score", sa.Float(), nullable=True),
        sa.Column("overall_quality_score", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("improvement_suggestions", sa.JSON(), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("would_use_again", sa.Boolean(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.Column("mood", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mixing_config_id"], ["mixing_configurations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mixing_feedback_mixing_config_id"),
        "mixing_feedback",
        ["mixing_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mixing_feedback_song_id"), "mixing_feedback", ["song_id"], unique=False
    )
    op.create_index(
        op.f("ix_mixing_feedback_user_id"), "mixing_feedback", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_mixing_feedback_genre"), "mixing_feedback", ["genre"], unique=False)
    op.create_table(
        "quality_metric_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mixing_config_id", sa.UUID(), nullable=True),
        sa.Column("song_id", sa.UUID(), nullable=True),
        sa.Column("pesq_score", sa.Float(), nullable=True),
        sa.Column("stoi_score", sa.Float(), nullable=True),
        sa.Column("mos_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("avg_user_rating", sa.Float(), nullable=True),
        sa.Column("feedback_count", sa.Integer(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mixing_config_id"], ["mixing_configurations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quality_metric_history_mixing_config_id"),
        "quality_metric_history",
        ["mixing_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_metric_history_song_id"),
        "quality_metric_history",
        ["song_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_metric_history_genre"), "quality_metric_history", ["genre"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quality_metric_history_genre"), table_name="quality_metric_history")
    op.drop_index(op.f("ix_quality_metric_history_song_id"), table_name="quality_metric_history")
    op.drop_index(
        op.f("ix_quality_metric_history_mixing_config_id"), table_name="quality_metric_history"
    )
    op.drop_table("quality_metric_history")
    op.drop_index(op.f("ix_mixing_feedback_genre"), table_name="mixing_feedback")
    op.drop_index(op.f("ix_mixing_feedback_user_id"), table_name="mixing_feedback")
    op.drop_index(op.f("ix_mixing_feedback_song_id"), table_name="mixing_feedback")
    op.drop_index(op.f("ix_mixing_feedback_mixing_config_id"), table_name="mixing_feedback")
    op.drop_table("mixing_feedback")
    # ### end Alembic commands ###
