"""Initial schema - users lyrics generation

Revision ID: 839ccef0216e
Revises:
Create Date: 2025-11-24 01:16:30.213427

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "839ccef0216e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("mood", sa.String(length=100), nullable=True),
        sa.Column("artist", sa.String(length=255), nullable=True),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("custom_metadata", sa.JSON(), nullable=False),
        sa.Column("chromadb_id", sa.String(length=255), nullable=True),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_chromadb_id"), "documents", ["chromadb_id"], unique=True)
    op.create_index(op.f("ix_documents_genre"), "documents", ["genre"], unique=False)
    op.create_index(op.f("ix_documents_is_indexed"), "documents", ["is_indexed"], unique=False)
    op.create_index(op.f("ix_documents_mood"), "documents", ["mood"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "lyrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("structure", sa.JSON(), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("mood", sa.String(length=100), nullable=True),
        sa.Column("theme", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("generation_params", sa.JSON(), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("generation_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("rhyme_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("creativity_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("coherence_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lyrics_genre"), "lyrics", ["genre"], unique=False)
    op.create_index(op.f("ix_lyrics_is_public"), "lyrics", ["is_public"], unique=False)
    op.create_index(op.f("ix_lyrics_mood"), "lyrics", ["mood"], unique=False)
    op.create_index(op.f("ix_lyrics_status"), "lyrics", ["status"], unique=False)
    op.create_index(op.f("ix_lyrics_user_id"), "lyrics", ["user_id"], unique=False)
    op.create_table(
        "generation_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lyrics_id", sa.UUID(), nullable=True),
        sa.Column("input_prompt", sa.Text(), nullable=False),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("mood", sa.String(length=100), nullable=True),
        sa.Column("theme", sa.String(length=255), nullable=True),
        sa.Column("custom_structure", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("agent_steps", sa.JSON(), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("total_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("llm_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("retrieval_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lyrics_id"], ["lyrics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_history_status"), "generation_history", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_generation_history_user_id"), "generation_history", ["user_id"], unique=False
    )
    op.create_table(
        "lyrics_sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lyrics_id", sa.UUID(), nullable=False),
        sa.Column("section_type", sa.String(length=50), nullable=False),
        sa.Column("section_order", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("rhyme_scheme", sa.String(length=50), nullable=True),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("generation_attempts", sa.Integer(), nullable=False),
        sa.Column("refinement_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lyrics_id"], ["lyrics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lyrics_sections_lyrics_id"), "lyrics_sections", ["lyrics_id"], unique=False
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lyrics_id", sa.UUID(), nullable=False),
        sa.Column("overall_rating", sa.Integer(), nullable=True),
        sa.Column("creativity_rating", sa.Integer(), nullable=True),
        sa.Column("relevance_rating", sa.Integer(), nullable=True),
        sa.Column("quality_rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("is_saved", sa.Boolean(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lyrics_id"], ["lyrics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_feedback_lyrics_id"), "user_feedback", ["lyrics_id"], unique=False
    )
    op.create_index(op.f("ix_user_feedback_user_id"), "user_feedback", ["user_id"], unique=False)
    op.create_table(
        "agent_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("generation_history_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("input_state", sa.JSON(), nullable=True),
        sa.Column("output_state", sa.JSON(), nullable=True),
        sa.Column("execution_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["generation_history_id"], ["generation_history.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_logs_agent_name"), "agent_logs", ["agent_name"], unique=False)
    op.create_index(
        op.f("ix_agent_logs_generation_history_id"),
        "agent_logs",
        ["generation_history_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_logs_generation_history_id"), table_name="agent_logs")
    op.drop_index(op.f("ix_agent_logs_agent_name"), table_name="agent_logs")
    op.drop_table("agent_logs")
    op.drop_index(op.f("ix_user_feedback_user_id"), table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_lyrics_id"), table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index(op.f("ix_lyrics_sections_lyrics_id"), table_name="lyrics_sections")
    op.drop_table("lyrics_sections")
    op.drop_index(op.f("ix_generation_history_user_id"), table_name="generation_history")
    op.drop_index(op.f("ix_generation_history_status"), table_name="generation_history")
    op.drop_table("generation_history")
    op.drop_index(op.f("ix_lyrics_user_id"), table_name="lyrics")
    op.drop_index(op.f("ix_lyrics_status"), table_name="lyrics")
    op.drop_index(op.f("ix_lyrics_mood"), table_name="lyrics")
    op.drop_index(op.f("ix_lyrics_is_public"), table_name="lyrics")
    op.drop_index(op.f("ix_lyrics_genre"), table_name="lyrics")
    op.drop_table("lyrics")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_documents_mood"), table_name="documents")
    op.drop_index(op.f("ix_documents_is_indexed"), table_name="documents")
    op.drop_index(op.f("ix_documents_genre"), table_name="documents")
    op.drop_index(op.f("ix_documents_chromadb_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
