"""add_song_generation_tables

Revision ID: 2c56f624cf99
Revises: 839ccef0216e
Create Date: 2025-11-26 23:49:02.115450

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c56f624cf99"
down_revision: Union[str, None] = "839ccef0216e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_is_active"), "api_keys", ["is_active"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audio_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_format", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("bit_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=False),
        sa.Column("audio_type", sa.String(length=50), nullable=False),
        sa.Column("waveform_data", sa.JSON(), nullable=True),
        sa.Column("file_metadata", sa.JSON(), nullable=False),
        sa.Column("storage_provider", sa.String(length=50), nullable=False),
        sa.Column("cdn_url", sa.String(length=500), nullable=True),
        sa.Column("is_cached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audio_files_audio_type"), "audio_files", ["audio_type"], unique=False)
    op.create_index(op.f("ix_audio_files_created_at"), "audio_files", ["created_at"], unique=False)
    op.create_index(op.f("ix_audio_files_file_path"), "audio_files", ["file_path"], unique=False)
    op.create_index(op.f("ix_audio_files_user_id"), "audio_files", ["user_id"], unique=False)
    op.create_table(
        "usage_statistics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("request_size_bytes", sa.Integer(), nullable=True),
        sa.Column("response_size_bytes", sa.Integer(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_statistics_endpoint"), "usage_statistics", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_usage_statistics_timestamp"), "usage_statistics", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_usage_statistics_user_id"), "usage_statistics", ["user_id"], unique=False
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preferred_genres", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("preferred_moods", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("default_structure", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("theme", sa.String(length=20), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="one_preference_per_user"),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=False
    )
    op.create_table(
        "voice_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("voice_model", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("age_range", sa.String(length=50), nullable=True),
        sa.Column("accent", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("base_pitch_hz", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pitch_range", sa.JSON(), nullable=True),
        sa.Column("timbre_profile", sa.JSON(), nullable=True),
        sa.Column("model_parameters", sa.JSON(), nullable=False),
        sa.Column("sample_audio_file_id", sa.UUID(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("average_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sample_audio_file_id"],
            ["audio_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_profiles_is_available"), "voice_profiles", ["is_available"], unique=False
    )
    op.create_index(
        op.f("ix_voice_profiles_is_premium"), "voice_profiles", ["is_premium"], unique=False
    )
    op.create_index(
        op.f("ix_voice_profiles_language"), "voice_profiles", ["language"], unique=False
    )
    op.create_table(
        "songs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lyrics_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist_name", sa.String(length=255), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("mood", sa.String(length=100), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("key", sa.String(length=10), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("voice_profile_id", sa.UUID(), nullable=True),
        sa.Column("music_style", sa.String(length=100), nullable=True),
        sa.Column("vocal_pitch_shift", sa.Integer(), nullable=False),
        sa.Column("vocal_effects", sa.JSON(), nullable=False),
        sa.Column("music_params", sa.JSON(), nullable=False),
        sa.Column("final_audio_file_id", sa.UUID(), nullable=True),
        sa.Column("vocal_track_file_id", sa.UUID(), nullable=True),
        sa.Column("instrumental_track_file_id", sa.UUID(), nullable=True),
        sa.Column("audio_quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("mixing_quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("overall_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("share_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("generation_status", sa.String(length=50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["final_audio_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrumental_track_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(["lyrics_id"], ["lyrics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["vocal_track_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_profile_id"],
            ["voice_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_songs_created_at"), "songs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_songs_generation_status"), "songs", ["generation_status"], unique=False
    )
    op.create_index(op.f("ix_songs_genre"), "songs", ["genre"], unique=False)
    op.create_index(op.f("ix_songs_is_public"), "songs", ["is_public"], unique=False)
    op.create_index(op.f("ix_songs_lyrics_id"), "songs", ["lyrics_id"], unique=False)
    op.create_index(op.f("ix_songs_user_id"), "songs", ["user_id"], unique=False)
    op.create_table(
        "music_tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("audio_file_id", sa.UUID(), nullable=True),
        sa.Column("track_name", sa.String(length=255), nullable=True),
        sa.Column("track_type", sa.String(length=50), nullable=False),
        sa.Column("track_order", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("pan", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("eq_settings", sa.JSON(), nullable=False),
        sa.Column("effects", sa.JSON(), nullable=False),
        sa.Column("start_time_seconds", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("end_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fade_in_seconds", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("fade_out_seconds", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_muted", sa.Boolean(), nullable=False),
        sa.Column("is_solo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("song_id", "track_order", name="unique_track_order"),
    )
    op.create_index(op.f("ix_music_tracks_song_id"), "music_tracks", ["song_id"], unique=False)
    op.create_index(
        op.f("ix_music_tracks_track_type"), "music_tracks", ["track_type"], unique=False
    )
    op.create_table(
        "song_generation_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=True),
        sa.Column("lyrics_id", sa.UUID(), nullable=True),
        sa.Column("generation_type", sa.String(length=50), nullable=False),
        sa.Column("input_params", sa.JSON(), nullable=False),
        sa.Column("voice_profile_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_stage", sa.String(length=100), nullable=True),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("agent_steps", sa.JSON(), nullable=False),
        sa.Column("total_time_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("vocal_generation_time", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("music_generation_time", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("mixing_time", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["lyrics_id"], ["lyrics.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["voice_profile_id"],
            ["voice_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_song_generation_history_lyrics_id"),
        "song_generation_history",
        ["lyrics_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_generation_history_song_id"),
        "song_generation_history",
        ["song_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_generation_history_started_at"),
        "song_generation_history",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_generation_history_status"),
        "song_generation_history",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_song_generation_history_user_id"),
        "song_generation_history",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_song_generation_history_user_id"), table_name="song_generation_history")
    op.drop_index(op.f("ix_song_generation_history_status"), table_name="song_generation_history")
    op.drop_index(
        op.f("ix_song_generation_history_started_at"), table_name="song_generation_history"
    )
    op.drop_index(op.f("ix_song_generation_history_song_id"), table_name="song_generation_history")
    op.drop_index(
        op.f("ix_song_generation_history_lyrics_id"), table_name="song_generation_history"
    )
    op.drop_table("song_generation_history")
    op.drop_index(op.f("ix_music_tracks_track_type"), table_name="music_tracks")
    op.drop_index(op.f("ix_music_tracks_song_id"), table_name="music_tracks")
    op.drop_table("music_tracks")
    op.drop_index(op.f("ix_songs_user_id"), table_name="songs")
    op.drop_index(op.f("ix_songs_lyrics_id"), table_name="songs")
    op.drop_index(op.f("ix_songs_is_public"), table_name="songs")
    op.drop_index(op.f("ix_songs_genre"), table_name="songs")
    op.drop_index(op.f("ix_songs_generation_status"), table_name="songs")
    op.drop_index(op.f("ix_songs_created_at"), table_name="songs")
    op.drop_table("songs")
    op.drop_index(op.f("ix_voice_profiles_language"), table_name="voice_profiles")
    op.drop_index(op.f("ix_voice_profiles_is_premium"), table_name="voice_profiles")
    op.drop_index(op.f("ix_voice_profiles_is_available"), table_name="voice_profiles")
    op.drop_table("voice_profiles")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_usage_statistics_user_id"), table_name="usage_statistics")
    op.drop_index(op.f("ix_usage_statistics_timestamp"), table_name="usage_statistics")
    op.drop_index(op.f("ix_usage_statistics_endpoint"), table_name="usage_statistics")
    op.drop_table("usage_statistics")
    op.drop_index(op.f("ix_audio_files_user_id"), table_name="audio_files")
    op.drop_index(op.f("ix_audio_files_file_path"), table_name="audio_files")
    op.drop_index(op.f("ix_audio_files_created_at"), table_name="audio_files")
    op.drop_index(op.f("ix_audio_files_audio_type"), table_name="audio_files")
    op.drop_table("audio_files")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_is_active"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
