"""add_mixing_config_memory_tables

Revision ID: 41181f128be7
Revises: 7e9e323b6cf6
Create Date: 2025-12-05 16:29:29.344008

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41181f128be7"
down_revision: Union[str, None] = "7e9e323b6cf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_tracks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=True),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.Column("audio_file_path", sa.String(length=500), nullable=False),
        sa.Column("audio_file_id", sa.UUID(), nullable=True),
        sa.Column("frequency_analysis", sa.JSON(), nullable=False),
        sa.Column("stereo_width_analysis", sa.JSON(), nullable=False),
        sa.Column("dynamic_range", sa.Float(), nullable=True),
        sa.Column("avg_loudness", sa.Float(), nullable=True),
        sa.Column("eq_profile", sa.JSON(), nullable=False),
        sa.Column("recommendations", sa.ARRAY(sa.JSON()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audio_file_id"], ["audio_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reference_tracks_genre"), "reference_tracks", ["genre"], unique=False)
    op.create_index(
        op.f("ix_reference_tracks_is_public"), "reference_tracks", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_reference_tracks_user_id"), "reference_tracks", ["user_id"], unique=False
    )
    op.create_table(
        "audio_feature_vectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audio_file_id", sa.UUID(), nullable=False),
        sa.Column("reference_track_id", sa.UUID(), nullable=True),
        sa.Column("chromadb_id", sa.String(length=255), nullable=True),
        sa.Column("vector_dimension", sa.Integer(), nullable=False),
        sa.Column("feature_type", sa.String(length=50), nullable=False),
        sa.Column("tempo", sa.Float(), nullable=True),
        sa.Column("spectral_centroid", sa.Float(), nullable=True),
        sa.Column("spectral_rolloff", sa.Float(), nullable=True),
        sa.Column("zero_crossing_rate", sa.Float(), nullable=True),
        sa.Column("mfcc_features", sa.ARRAY(sa.Float()), nullable=False),
        sa.Column("frequency_bands", sa.JSON(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audio_file_id"], ["audio_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reference_track_id"], ["reference_tracks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audio_feature_vectors_audio_file_id"),
        "audio_feature_vectors",
        ["audio_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audio_feature_vectors_chromadb_id"),
        "audio_feature_vectors",
        ["chromadb_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_audio_feature_vectors_feature_type"),
        "audio_feature_vectors",
        ["feature_type"],
        unique=False,
    )
    op.create_table(
        "mixing_configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("song_id", sa.UUID(), nullable=True),
        sa.Column("config_type", sa.String(length=50), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.Column("eq_settings", sa.JSON(), nullable=False),
        sa.Column("compression_settings", sa.JSON(), nullable=False),
        sa.Column("stereo_width_settings", sa.JSON(), nullable=False),
        sa.Column("reverb_settings", sa.JSON(), nullable=False),
        sa.Column("delay_settings", sa.JSON(), nullable=False),
        sa.Column("sidechain_settings", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mixing_configurations_config_type"),
        "mixing_configurations",
        ["config_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mixing_configurations_genre"), "mixing_configurations", ["genre"], unique=False
    )
    op.create_index(
        op.f("ix_mixing_configurations_is_default"),
        "mixing_configurations",
        ["is_default"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mixing_configurations_is_public"),
        "mixing_configurations",
        ["is_public"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mixing_configurations_song_id"), "mixing_configurations", ["song_id"], unique=False
    )
    op.create_index(
        op.f("ix_mixing_configurations_user_id"), "mixing_configurations", ["user_id"], unique=False
    )
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_mixing_configurations_user_id"), table_name="mixing_configurations")
    op.drop_index(op.f("ix_mixing_configurations_song_id"), table_name="mixing_configurations")
    op.drop_index(op.f("ix_mixing_configurations_is_public"), table_name="mixing_configurations")
    op.drop_index(op.f("ix_mixing_configurations_is_default"), table_name="mixing_configurations")
    op.drop_index(op.f("ix_mixing_configurations_genre"), table_name="mixing_configurations")
    op.drop_index(op.f("ix_mixing_configurations_config_type"), table_name="mixing_configurations")
    op.drop_table("mixing_configurations")
    op.drop_index(op.f("ix_audio_feature_vectors_feature_type"), table_name="audio_feature_vectors")
    op.drop_index(op.f("ix_audio_feature_vectors_chromadb_id"), table_name="audio_feature_vectors")
    op.drop_index(
        op.f("ix_audio_feature_vectors_audio_file_id"), table_name="audio_feature_vectors"
    )
    op.drop_table("audio_feature_vectors")
    op.drop_index(op.f("ix_reference_tracks_user_id"), table_name="reference_tracks")
    op.drop_index(op.f("ix_reference_tracks_is_public"), table_name="reference_tracks")
    op.drop_index(op.f("ix_reference_tracks_genre"), table_name="reference_tracks")
    op.drop_table("reference_tracks")
    # ### end Alembic commands ###
