"""add key_prefix to api_key model

Revision ID: 7e9e323b6cf6
Revises: 6f904877253e
Create Date: 2025-11-27 22:21:16.052576

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9e323b6cf6"
down_revision: Union[str, None] = "6f904877253e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
